// Rapid-fire clinical question bank: short, single-best-answer, mixed across the five rotations. Each carries the reasoning.
import type { MCQ, Rotation, Skill } from "./types";
import { mcq, o } from "./templates";
import { seeded } from "./whyLadders";

export interface BankQ extends MCQ { rotation: Rotation; topic: string }

const Q = (id: string, rotation: Rotation, topic: string, skill: Skill, stem: string, right: string, wrong: [string, string, string], why: string, hint?: string): BankQ => ({
  ...mcq(`bk-${id}`, skill, stem, seeded([o(right, true, why), ...wrong.map((w) => o(w, false, "Not the best answer here."))], id), [hint ?? `Which diagnosis or action fits all the features, not just one?`, `The answer begins “${right.slice(0, 14)}…”.`], why),
  rotation, topic,
});

export const BANK: BankQ[] = [
  // ---------------- Medicine
  Q("m1", "medicine", "Cardiology", "differentials", "A 60-year-old has chest pain radiating to the back, BP 170/100 in the right arm and 120/70 in the left. What do you suspect?", "Aortic dissection", ["Stable angina", "Pericarditis", "Oesophageal spasm"], "A tearing pain radiating to the back with a blood-pressure difference between arms points to dissection. Do not give anticoagulant or thrombolytic."),
  Q("m2", "medicine", "Cardiology", "interpretation", "ECG: PR interval lengthens progressively until a P wave is not followed by a QRS. This is:", "Mobitz type I (Wenckebach)", ["Mobitz type II", "Third-degree block", "First-degree block"], "Progressive PR lengthening then a dropped beat is Wenckebach, usually at the AV node and often benign."),
  Q("m3", "medicine", "Respiratory", "interpretation", "ABG: pH 7.28, pCO₂ 8.5 kPa, HCO₃⁻ 30. This is:", "Acute-on-chronic respiratory acidosis", ["Metabolic acidosis", "Respiratory alkalosis", "Metabolic alkalosis"], "A low pH with high CO₂ is respiratory acidosis; the raised bicarbonate shows renal compensation, so it is chronic (COPD)."),
  Q("m4", "medicine", "Respiratory", "investigations", "The most useful first test in a patient with a unilateral pleural effusion is:", "Diagnostic pleural aspiration", ["CT head", "Spirometry", "Bronchoscopy"], "Sampling the fluid (protein, LDH, cells, ADA, culture) identifies the cause."),
  Q("m5", "medicine", "Endocrine", "emergency", "In DKA, which should be done before starting an insulin infusion?", "Check potassium and start fluids", ["Give a bicarbonate bolus", "Give oral glucose", "Start potassium-free fluids only"], "Insulin drives K⁺ into cells; if K⁺ is < 3.5 you must replace it first. Fluids come first."),
  Q("m6", "medicine", "Endocrine", "differentials", "Weight loss, tremor, sweating, tachycardia and a diffuse goitre with exophthalmos:", "Graves’ disease", ["Toxic adenoma", "Hashimoto’s thyroiditis", "Anxiety disorder"], "Exophthalmos is specific for Graves’ disease (an autoimmune TSH-receptor-stimulating disease)."),
  Q("m7", "medicine", "Renal", "investigations", "Which finding best distinguishes acute kidney injury from chronic kidney disease?", "Normal-sized kidneys on ultrasound with a recent rise in creatinine", ["Anaemia", "Proteinuria", "Hypertension"], "Small shrunken kidneys suggest chronicity; normal-sized kidneys and a rising creatinine suggest AKI."),
  Q("m8", "medicine", "Neurology", "emergency", "A patient has a CT-confirmed ischaemic stroke 2 hours after onset. The treatment is:", "Intravenous thrombolysis if no contraindication", ["Immediate heparin infusion", "Immediate lumbar puncture", "Dexamethasone"], "Alteplase within 4.5 hours of onset improves outcomes; a CT first excludes haemorrhage."),
  Q("m9", "medicine", "Infection", "differentials", "Fever, headache, neck stiffness and a petechial rash in a young adult:", "Meningococcal meningitis/septicaemia", ["Viral meningitis", "Migraine", "Tension headache"], "Petechiae suggest meningococcaemia: give antibiotics immediately — do not wait for the LP or CT."),
  Q("m10", "medicine", "Infection", "management", "A patient with TB starts RHZE. Which supplement prevents peripheral neuropathy?", "Pyridoxine (vitamin B₆)", ["Vitamin C", "Folic acid", "Calcium"], "Isoniazid depletes pyridoxine and causes neuropathy; give B₆ routinely."),
  Q("m11", "medicine", "Haematology", "differentials", "Microcytic anaemia with low ferritin in a 45-year-old man requires:", "Investigation for gastrointestinal blood loss", ["Iron alone and discharge", "B₁₂ injections", "Bone marrow biopsy first"], "Iron deficiency in a man or postmenopausal woman is GI cancer or bleeding until proved otherwise."),
  Q("m12", "medicine", "GI", "management", "A cirrhotic patient with ascites has fever and abdominal pain. The key test is:", "Diagnostic ascitic tap (neutrophils > 250/mm³)", ["CT head", "Urine dipstick", "ECG"], "Spontaneous bacterial peritonitis: ascitic neutrophils > 250 mm³; treat with ceftriaxone and albumin."),
  Q("m13", "medicine", "Pharmacology", "management", "A patient on an ACE inhibitor develops a persistent dry cough. The best step:", "Switch to an ARB", ["Add a second ACE inhibitor", "Stop all antihypertensives", "Add a diuretic only"], "Cough is bradykinin-mediated; ARBs do not cause it."),
  // ---------------- Obs & Gynae
  Q("o1", "obgyn", "Obstetrics", "emergency", "Eclamptic fit at 37 weeks. The first-line anticonvulsant is:", "Magnesium sulphate", ["Phenytoin", "Diazepam alone", "Carbamazepine"], "Magnesium reduces recurrent seizures and is superior to diazepam or phenytoin."),
  Q("o2", "obgyn", "Obstetrics", "differentials", "Painless fresh vaginal bleeding at 34 weeks with a soft uterus:", "Placenta praevia", ["Placental abruption", "Labour", "Uterine rupture"], "Praevia classically causes painless bleeding. Abruption is painful with a woody uterus."),
  Q("o3", "obgyn", "Obstetrics", "management", "Primary PPH after vaginal delivery with a soft boggy uterus. First action:", "Uterine massage, oxytocin and resuscitation", ["Hysterectomy", "Wait and watch", "Give ergometrine to a hypertensive woman"], "Atony is the commonest cause: massage, uterotonics, tranexamic acid, then escalate."),
  Q("o4", "obgyn", "Obstetrics", "differentials", "Positive pregnancy test, unilateral iliac fossa pain and an empty uterus on ultrasound:", "Ectopic pregnancy", ["Threatened miscarriage", "Appendicitis", "Molar pregnancy"], "Ectopic until proved otherwise — it is lethal."),
  Q("o5", "obgyn", "Obstetrics", "management", "A pregnant woman’s BP is 160/110 with proteinuria. Which antihypertensive is NOT safe?", "Enalapril (ACE inhibitor)", ["Labetalol", "Nifedipine", "Methyldopa"], "ACE inhibitors cause fetal renal damage; use labetalol, nifedipine or methyldopa."),
  Q("o6", "obgyn", "Obstetrics", "emergency", "Shoulder dystocia is managed first by:", "McRoberts manoeuvre with suprapubic pressure", ["Fundal pressure", "Immediate caesarean", "Traction on the head"], "Call for help, McRoberts and suprapubic pressure; avoid fundal pressure."),
  Q("o7", "obgyn", "Gynaecology", "differentials", "Fever, bilateral lower abdominal pain, cervical motion tenderness and purulent discharge:", "Pelvic inflammatory disease", ["Endometriosis", "Fibroids", "Ovarian cancer"], "PID: cervical motion tenderness with adnexal tenderness; treat early to protect fertility."),
  Q("o8", "obgyn", "Gynaecology", "investigations", "Postmenopausal bleeding needs:", "Endometrial assessment (transvaginal ultrasound ± biopsy)", ["Reassurance", "HRT only", "No investigation"], "Postmenopausal bleeding is endometrial cancer until proved otherwise."),
  Q("o9", "obgyn", "Obstetrics", "pathophysiology", "The most common cause of maternal death in Kenya is:", "Haemorrhage (with hypertensive disorders and sepsis)", ["Malaria alone", "Road traffic accidents", "Stroke"], "Obstetric haemorrhage remains the leading direct cause worldwide."),
  Q("o10", "obgyn", "Obstetrics", "management", "A Rhesus-negative mother has an antepartum haemorrhage. What must be given?", "Anti-D immunoglobulin", ["Vitamin K", "Folic acid", "Corticosteroids only"], "Sensitisation to fetal Rh-positive cells is prevented by anti-D."),
  // ---------------- Paediatrics
  Q("p1", "paeds", "Respiratory", "management", "A child has fast breathing and chest indrawing. According to IMCI, classify as:", "Severe pneumonia — admit and give antibiotics", ["No pneumonia", "Pneumonia — treat at home", "Asthma"], "Chest indrawing is a sign of severe pneumonia."),
  Q("p2", "paeds", "Infection", "emergency", "The first step for a convulsing child with fever is:", "Airway, oxygen, check glucose, then give a benzodiazepine", ["Lumbar puncture", "CT head", "Paracetamol only"], "ABC and glucose first, then terminate the seizure."),
  Q("p3", "paeds", "Nutrition", "management", "A child with kwashiorkor and shock should receive:", "Cautious IV fluids (10–15 ml/kg over 1 h) with reassessment", ["20 ml/kg bolus", "No fluids at all", "Free water orally"], "Children with SAM are prone to heart failure with large boluses."),
  Q("p4", "paeds", "Neonatology", "differentials", "A baby is yellow at 12 hours of age. The most likely cause is:", "Haemolysis (ABO/Rh incompatibility)", ["Physiological jaundice", "Breast-milk jaundice", "Biliary atresia"], "Jaundice in the first 24 hours is pathological until proved otherwise."),
  Q("p5", "paeds", "Gastroenterology", "management", "Some dehydration in a child with diarrhoea is treated with:", "ORS 75 ml/kg over 4 hours plus zinc", ["IV 20 ml/kg bolus", "Antibiotics for everyone", "Anti-diarrhoeals"], "Most diarrhoea needs fluids and zinc, not antibiotics."),
  Q("p6", "paeds", "Haematology", "emergency", "A child with sickle cell disease has fever 39 °C. The most important action is:", "Urgent assessment with blood culture and IV antibiotics", ["Paracetamol and home", "Blood transfusion", "Wait 48 hours"], "Functional asplenia — fever is sepsis until proved otherwise."),
  Q("p7", "paeds", "Respiratory", "management", "The best bronchodilator in an acute severe asthma attack in a child is:", "Nebulised salbutamol, with ipratropium and steroids", ["Oral theophylline", "Antibiotics", "Cough suppressants"], "Salbutamol first; add ipratropium in severe cases; give steroids early."),
  Q("p8", "paeds", "Development", "pathophysiology", "A 12-month-old cannot sit, has poor head control and lacks social smile. This suggests:", "Global developmental delay", ["Normal variation", "Hearing loss only", "Autism only"], "Missing multiple milestones across domains = global delay; investigate causes."),
  Q("p9", "paeds", "Cardiology", "differentials", "A newborn is blue and not improving with oxygen. This suggests:", "Cyanotic congenital heart disease", ["Respiratory distress syndrome", "Transient tachypnoea", "Anaemia"], "Failure of the hyperoxia test suggests a right-to-left shunt."),
  Q("p10", "paeds", "Malaria", "management", "Severe malaria in a child is treated first with:", "IV artesunate", ["Oral artemether-lumefantrine alone", "IV quinine as the first choice", "Chloroquine"], "Artesunate reduces mortality compared with quinine."),
  // ---------------- Surgery
  Q("s1", "surgery", "Trauma", "emergency", "In the primary survey, which is addressed FIRST?", "Airway with cervical-spine protection", ["Circulation", "Disability", "Exposure"], "ABCDE order is fixed; airway always comes first."),
  Q("s2", "surgery", "Abdomen", "differentials", "Pain beginning around the umbilicus, then localising to the right iliac fossa:", "Acute appendicitis", ["Gastroenteritis", "Constipation", "Renal colic"], "Visceral pain from the midgut moves to the right iliac fossa when the parietal peritoneum is involved."),
  Q("s3", "surgery", "Abdomen", "management", "Free air under the diaphragm on an erect CXR:", "Perforated viscus — urgent laparotomy", ["Normal finding", "Pneumonia", "Pancreatitis"], "A perforation needs resuscitation, antibiotics and surgery."),
  Q("s4", "surgery", "Burns", "management", "For a child with 15% TBSA burns, the first-day fluids are guided by:", "A burn formula (e.g. Parkland) plus maintenance, titrated to urine output", ["Oral sips only", "No fluids", "Fixed 500 ml bolus"], "Parkland: 4 ml × kg × %TBSA in 24 h, half in the first 8 hours."),
  Q("s5", "surgery", "Breast", "investigations", "A 45-year-old with a breast lump needs:", "Triple assessment: clinical examination, imaging and core biopsy", ["Mammogram only", "FNAC only", "Observation for 3 months"], "Triple assessment is the standard of care."),
  Q("s6", "surgery", "Vascular", "differentials", "A cold, pale, painful leg with absent pulses of sudden onset:", "Acute limb ischaemia", ["DVT", "Cellulitis", "Gout"], "The six Ps: pain, pallor, pulselessness, paraesthesia, paralysis, perishing cold; emergency vascular review."),
  Q("s7", "surgery", "Urology", "differentials", "A man cannot pass urine, with a distended painful bladder and an enlarged prostate:", "Acute urinary retention from BPH", ["UTI", "Renal colic", "Appendicitis"], "Catheterise and measure residual volume; look for the cause."),
  Q("s8", "surgery", "Thyroid", "management", "A solitary thyroid nodule is first investigated with:", "TSH and ultrasound-guided fine-needle aspiration", ["Radioiodine immediately", "CT chest", "Surgery without tests"], "Function and cytology decide management."),
  Q("s9", "surgery", "Hernia", "emergency", "A tender, irreducible, discoloured groin swelling with vomiting:", "Strangulated hernia — urgent surgery", ["Reducible hernia", "Lipoma", "Lymph node"], "Ischaemic bowel requires emergency operation."),
  Q("s10", "surgery", "Trauma", "emergency", "Hypotension, absent breath sounds and distended neck veins after chest trauma:", "Tension pneumothorax — needle decompression now", ["Cardiac tamponade only", "Simple rib fracture", "Pulmonary contusion"], "Decompress immediately; do not wait for an X-ray."),
  // ---------------- Psychiatry
  Q("y1", "psychiatry", "Psychosis", "differentials", "A fluctuating level of consciousness with visual hallucinations and disorientation:", "Delirium", ["Schizophrenia", "Mania", "Depression"], "Delirium is acute, fluctuating and usually medical; look for the cause."),
  Q("y2", "psychiatry", "Mood", "differentials", "Elevated mood, decreased need for sleep, grandiosity and pressured speech for 10 days:", "Mania (bipolar disorder)", ["Schizophrenia", "ADHD", "Panic disorder"], "Duration ≥ 7 days with these features is mania."),
  Q("y3", "psychiatry", "Risk", "management", "The best way to assess suicide risk is to:", "Ask directly about thoughts, plans, intent and means", ["Avoid the topic", "Ask only family", "Wait for them to mention it"], "Asking does not plant the idea; it opens the door to help."),
  Q("y4", "psychiatry", "Pharmacology", "management", "First-line drug for acute agitation due to alcohol withdrawal:", "A benzodiazepine, with thiamine", ["Haloperidol alone", "Phenytoin", "Amitriptyline"], "Benzodiazepines treat withdrawal and prevent seizures; antipsychotics lower the seizure threshold."),
  Q("y5", "psychiatry", "Pharmacology", "management", "A patient on lithium develops coarse tremor, vomiting and ataxia. This suggests:", "Lithium toxicity", ["Parkinson disease", "Alcohol withdrawal", "Serotonin syndrome"], "Dehydration, NSAIDs and ACE inhibitors raise lithium levels; check level and U&E."),
  Q("y6", "psychiatry", "Anxiety", "differentials", "Before diagnosing panic disorder you must exclude:", "Thyrotoxicosis, arrhythmia, hypoglycaemia and substance effects", ["Nothing is needed", "Only epilepsy", "Only dementia"], "Anxiety has many organic mimics."),
  Q("y7", "psychiatry", "Law", "management", "A psychotic patient poses a serious risk to others and lacks insight. The proper approach is:", "Detention and treatment under mental health legislation, with the least restrictive care", ["Discharge him", "Restrain without documentation", "Treat him covertly"], "Risk, illness and lack of capacity justify compulsory care under the Mental Health Act."),
  Q("y8", "psychiatry", "Child", "differentials", "A child with inattention and hyperactivity in school and at home, with onset before 12 years:", "ADHD", ["Normal child behaviour", "Conduct disorder only", "Autism only"], "Persistent symptoms in two or more settings before 12 years with impairment."),
  Q("y9", "psychiatry", "Pharmacology", "management", "A woman on valproate plans pregnancy. The key advice is:", "Switch to a safer alternative before conception because of teratogenicity", ["Continue unchanged", "Double the dose", "Stop all medication permanently"], "Valproate causes neural-tube and developmental harm."),
  Q("y10", "psychiatry", "Substance", "management", "Before giving glucose to an alcoholic with confusion, give:", "IV thiamine", ["Insulin", "Haloperidol", "Aspirin"], "Glucose can precipitate Wernicke’s encephalopathy in thiamine-deficient patients."),

  // ---------------- Year 4 must-knows: Medicine
  Q("m14", "medicine", "Respiratory", "differentials", "Fever, productive cough, pleuritic chest pain, bronchial breathing and focal crackles most strongly suggest:", "Lobar pneumonia", ["Pulmonary embolism", "Heart failure", "Asthma"], "An acute febrile illness with focal consolidation signs is pneumonia. On the ward, assess oxygenation and severity before choosing site of care."),
  Q("m15", "medicine", "Respiratory", "differentials", "A long-term smoker has chronic productive cough, progressive dyspnoea, wheeze and prolonged expiration. The likely diagnosis is:", "COPD", ["Pulmonary oedema", "Pleural effusion", "Pneumothorax"], "Smoking exposure plus chronic cough and fixed airflow symptoms suggest COPD; confirm stable disease with post-bronchodilator spirometry."),
  Q("m16", "medicine", "Neurology", "differentials", "A patient has a generalised convulsion. Which bedside abnormality must be excluded immediately because it is rapidly reversible?", "Hypoglycaemia", ["Hypercholesterolaemia", "Iron deficiency", "Osteoarthritis"], "Check capillary glucose early in any seizure or altered consciousness; hypoglycaemia can mimic or provoke neurological emergencies."),
  Q("m17", "medicine", "Renal", "differentials", "Generalised oedema, frothy urine, heavy proteinuria and low serum albumin indicate:", "Nephrotic syndrome", ["Nephritic syndrome", "Pyelonephritis", "Renal colic"], "Heavy protein loss causes hypoalbuminaemia and oedema; then determine the underlying glomerular disease and assess thrombosis/infection risk."),
  Q("m18", "medicine", "Cardiology", "management", "A patient has BP 220/130 mmHg with pulmonary oedema and confusion. This is:", "Hypertensive emergency requiring monitored IV blood-pressure reduction", ["Uncomplicated hypertension", "White-coat hypertension", "Hypotension"], "Severe BP plus acute target-organ injury is a hypertensive emergency. Treat the organ emergency and lower BP in a controlled monitored fashion."),
  Q("m19", "medicine", "Infection", "emergency", "A febrile patient is confused, hypotensive, tachypnoeic and has delayed capillary refill. Your immediate priority is:", "Recognise sepsis, perform ABC assessment and start urgent resuscitation and antimicrobials", ["Wait for culture results", "Give antipyretics only", "Arrange outpatient review"], "Shock physiology with suspected infection is time-critical; obtain cultures when feasible without delaying resuscitation and appropriate antibiotics."),
  Q("m20", "medicine", "Haematology", "interpretation", "Hb is low, MCV 68 fL and ferritin is low. The anaemia is most consistent with:", "Iron-deficiency anaemia", ["Vitamin B12 deficiency", "Aplastic anaemia", "Acute haemolysis"], "Low MCV plus depleted iron stores supports iron deficiency. Do not stop at the label—look for the source of iron loss."),
  Q("m21", "medicine", "GI", "emergency", "Haematemesis with tachycardia and hypotension should initially be managed by:", "ABC resuscitation, large-bore IV access, blood tests/cross-match and urgent upper-GI bleed management", ["Immediate oral feeding", "Colonoscopy first", "Discharge with antacid"], "Stabilise haemodynamics before definitive endoscopy; assess for variceal bleeding and major blood loss."),
  Q("m22", "medicine", "Malaria", "differentials", "A patient with malaria has confusion, repeated seizures, jaundice and hypoglycaemia. This should be classified as:", "Severe malaria", ["Uncomplicated malaria", "Viral URTI", "Simple febrile illness"], "Neurological dysfunction, hypoglycaemia and significant organ involvement are severe features requiring urgent parenteral treatment and supportive care."),
  Q("m23", "medicine", "History", "differentials", "In a breathless patient, orthopnoea, paroxysmal nocturnal dyspnoea and bilateral ankle swelling particularly point toward:", "Heart failure", ["Isolated gastritis", "Migraine", "Cellulitis"], "These questions connect symptoms to pulmonary and systemic venous congestion and should be routine in a dyspnoea history."),

  // ---------------- Year 4 must-knows: Obstetrics & Gynaecology
  Q("o11", "obgyn", "Obstetrics", "differentials", "Third-trimester bleeding is painful, the uterus is tender and tense, and the fetus is distressed. Suspect:", "Placental abruption", ["Placenta praevia", "Cervical ectropion", "Normal labour show"], "Abruption classically causes painful bleeding with uterine tenderness/hypertonus; concealed haemorrhage means visible blood may underestimate severity."),
  Q("o12", "obgyn", "Obstetrics", "emergency", "A woman in labour has sudden severe abdominal pain, fetal bradycardia, maternal shock and loss of fetal station after a previous caesarean. Suspect:", "Uterine rupture", ["Normal transition", "Placenta praevia", "Hyperemesis"], "Previous uterine scar plus sudden pain, fetal compromise and maternal deterioration is rupture until proven otherwise."),
  Q("o13", "obgyn", "Obstetrics", "management", "A labouring woman has slow cervical dilatation. The most useful tool for following progress and maternal/fetal observations is:", "A labour care guide/partograph with repeated clinical assessment", ["A single ultrasound only", "CT pelvis", "Urine pregnancy test"], "Labour assessment is longitudinal: cervical progress, contractions, fetal status and maternal observations must be interpreted together."),
  Q("o14", "obgyn", "Obstetrics", "emergency", "After delivery, think of the 4 Ts when evaluating postpartum haemorrhage. They are:", "Tone, Trauma, Tissue and Thrombin", ["Temperature, Tension, Thyroid, Thirst", "Tube, Tumour, Torsion, Trauma", "Tone, Time, Test, Treatment"], "The 4 Ts rapidly organise causes: uterine atony, genital tract trauma, retained tissue and coagulopathy."),
  Q("o15", "obgyn", "Gynaecology", "differentials", "Progressive dysmenorrhoea, deep dyspareunia and infertility in a reproductive-age woman suggest:", "Endometriosis", ["Ectopic pregnancy", "Cervical cancer", "Vaginitis"], "Cyclical pelvic pain with deep dyspareunia and infertility is a classic endometriosis pattern."),
  Q("o16", "obgyn", "Gynaecology", "differentials", "Heavy menstrual bleeding with an enlarged irregular firm uterus most strongly suggests:", "Uterine fibroids", ["PID", "Ectopic pregnancy", "Ovarian torsion"], "Leiomyomas commonly cause heavy bleeding, pressure symptoms and an irregularly enlarged uterus."),
  Q("o17", "obgyn", "Gynaecology", "emergency", "Sudden severe unilateral pelvic pain with vomiting and an adnexal mass should make you think first of:", "Ovarian torsion", ["Chronic PID", "Fibroids", "Cervical ectropion"], "Torsion is a time-critical surgical diagnosis because prolonged vascular compromise can destroy the ovary."),
  Q("o18", "obgyn", "Obstetrics", "investigations", "At the first antenatal assessment, which approach is most appropriate?", "Establish gestational age, maternal baseline health, obstetric risk and recommended screening tests", ["Only measure weight", "Only determine fetal sex", "Delay assessment until third trimester"], "Booking establishes dating and identifies anaemia, hypertension, infections and other maternal/fetal risks early."),
  Q("o19", "obgyn", "Obstetrics", "differentials", "Fever, uterine tenderness and foul-smelling lochia after delivery suggest:", "Puerperal endometritis/sepsis", ["Normal puerperium", "Placenta praevia", "Hyperemesis gravidarum"], "Postpartum fever with uterine tenderness and offensive lochia is genital-tract infection until assessed and treated."),
  Q("o20", "obgyn", "Gynaecology", "differentials", "Postcoital bleeding, offensive discharge and an abnormal friable cervix require evaluation for:", "Cervical cancer", ["Endometriosis only", "Normal ovulation", "Appendicitis"], "Persistent postcoital bleeding is a red flag; examine the cervix and arrange appropriate diagnostic assessment."),

  // ---------------- Year 4 must-knows: Paediatrics
  Q("p11", "paeds", "Emergency", "emergency", "A sick child arrives lethargic with poor perfusion. What comes first?", "Paediatric ABCDE assessment with immediate correction of life threats", ["Full developmental history first", "Routine discharge", "Wait for laboratory results"], "Stabilisation precedes diagnostic detail. Check airway, breathing, circulation, disability including glucose, then exposure."),
  Q("p12", "paeds", "Neonatology", "emergency", "A newborn is not breathing after drying and stimulation. The key next intervention is:", "Effective positive-pressure ventilation", ["Chest compressions immediately in every baby", "Antibiotics only", "Observe for 30 minutes"], "Ventilation is the key intervention in neonatal resuscitation when apnoea/gasping persists."),
  Q("p13", "paeds", "Nutrition", "interpretation", "Bilateral pitting oedema of nutritional origin in a child is sufficient to classify:", "Severe acute malnutrition", ["Normal nutrition", "Overweight", "Mild dehydration only"], "Nutritional oedema is a defining feature of severe acute malnutrition; assess for complications before feeding rehabilitation."),
  Q("p14", "paeds", "Infection", "differentials", "Fever, neck stiffness, altered consciousness and a bulging fontanelle in an infant suggest:", "Meningitis", ["Simple colic", "Teething", "Uncomplicated eczema"], "Infants may show nonspecific signs; altered neurological state and meningeal/fontanelle findings demand urgent assessment."),
  Q("p15", "paeds", "Cardiology", "differentials", "Poor feeding, sweating during feeds, tachypnoea and poor weight gain in an infant suggest:", "Heart failure from congenital heart disease", ["Normal feeding behaviour", "Otitis externa", "Constipation"], "Feeding is exertion for an infant; sweating and tachypnoea during feeds are important cardiac clues."),
  Q("p16", "paeds", "Renal", "differentials", "Periorbital oedema, cola-coloured urine and hypertension after a recent sore throat suggest:", "Acute glomerulonephritis", ["Nephrotic syndrome only", "Gastroenteritis", "Diabetes insipidus"], "Haematuria, oedema and hypertension form a nephritic pattern; post-streptococcal disease is a classic cause."),
  Q("p17", "paeds", "Haematology", "differentials", "A child with severe pallor, tachycardia and respiratory distress needs you to first determine:", "Whether the anaemia is causing haemodynamic or respiratory compromise", ["Hair colour", "School marks", "Dental age"], "Severity is clinical as well as numerical. Stabilise a compromised child while investigating the cause of anaemia."),
  Q("p18", "paeds", "Development", "investigations", "When a child misses milestones, the best initial approach is to:", "Assess all developmental domains, hearing/vision, growth and neurological examination", ["Diagnose autism immediately", "Ignore until school age", "Order CT for every child"], "Developmental delay requires a structured multi-domain assessment before targeted investigations."),
  Q("p19", "paeds", "Gastroenterology", "management", "In childhood diarrhoea, which clinical assessment determines the fluid plan?", "Degree of dehydration based on clinical signs", ["Stool colour alone", "Age alone", "Number of siblings"], "Classify dehydration clinically, then choose oral or IV rehydration accordingly and reassess."),
  Q("p20", "paeds", "Malaria", "emergency", "A child with suspected severe malaria is unconscious. Which bedside test must be checked immediately as well?", "Blood glucose", ["Serum cholesterol", "Skin-prick allergy test", "Visual acuity"], "Hypoglycaemia is common and dangerous in severe malaria and can independently cause coma or seizures."),

  // ---------------- Year 4 must-knows: Surgery
  Q("s11", "surgery", "Abdomen", "differentials", "Severe epigastric pain radiating to the back with vomiting and epigastric tenderness suggests:", "Acute pancreatitis", ["Appendicitis", "Cystitis", "Migraine"], "The pain pattern is classic; confirm with appropriate pancreatic enzymes and assess severity/underlying cause."),
  Q("s12", "surgery", "Abdomen", "differentials", "Right upper-quadrant pain, fever and a positive Murphy sign suggest:", "Acute cholecystitis", ["Acute appendicitis", "Renal failure", "Bowel obstruction"], "Local gallbladder inflammation produces RUQ tenderness and inspiratory arrest on palpation."),
  Q("s13", "surgery", "Abdomen", "differentials", "Colicky abdominal pain, vomiting, distension and absolute constipation indicate:", "Intestinal obstruction", ["Uncomplicated gastritis", "Hepatitis", "Migraine"], "The four core obstruction features are colicky pain, vomiting, distension and failure to pass stool/flatus; look urgently for strangulation."),
  Q("s14", "surgery", "Trauma", "emergency", "An unstable trauma patient with suspected intra-abdominal bleeding should be approached by:", "ABCDE resuscitation with rapid haemorrhage identification/control", ["Detailed elective history before treatment", "Oral fluids", "Delay until all imaging is complete"], "Trauma care prioritises immediately reversible threats and haemorrhage control rather than diagnostic perfection."),
  Q("s15", "surgery", "Wounds", "management", "A diabetic foot ulcer should be assessed for which major limb-threatening problems?", "Infection, ischaemia, neuropathy and depth/osteomyelitis", ["Myopia and hearing loss", "Asthma only", "Migraine"], "A useful diabetic-foot framework asks whether the foot is infected, perfused, sensate and how deep the tissue destruction extends."),
  Q("s16", "surgery", "Urology", "differentials", "Sudden severe loin-to-groin colicky pain with haematuria suggests:", "Ureteric stone", ["Appendicitis only", "Pneumonia", "Peptic ulcer"], "Renal colic classically radiates from loin to groin and may cause microscopic or visible haematuria."),
  Q("s17", "surgery", "Urology", "differentials", "Painless visible haematuria in an older adult should be considered:", "Urinary tract malignancy until appropriately investigated", ["Normal ageing", "Simple dehydration", "Migraine"], "Painless macroscopic haematuria is an important malignancy red flag requiring urological evaluation."),
  Q("s18", "surgery", "Hernia", "differentials", "Which feature most strongly suggests a hernia has strangulated?", "A painful irreducible swelling with systemic illness or bowel obstruction", ["A painless reducible cough impulse", "Long-standing stable swelling", "Swelling disappearing when standing"], "Pain, irreducibility, obstruction and toxicity suggest compromised blood supply and demand urgent surgical review."),
  Q("s19", "surgery", "Postoperative", "emergency", "A postoperative patient suddenly becomes tachycardic, hypotensive and increasingly abdominally distended. First concern:", "Postoperative haemorrhage", ["Normal recovery", "Mild anxiety only", "Constipation only"], "Unexpected shock after surgery is bleeding until excluded; resuscitate while urgently looking for the source."),
  Q("s20", "surgery", "Breast", "differentials", "A hard irregular breast mass fixed to surrounding tissue with skin tethering is concerning for:", "Breast malignancy", ["Simple cyst only", "Normal breast tissue", "Mastalgia alone"], "Hard irregular fixation and skin/nipple changes are malignant red flags; proceed to triple assessment."),

  // ---------------- Year 4 must-knows: Psychiatry
  Q("y11", "psychiatry", "Mental state examination", "interpretation", "Which domains belong in a mental state examination?", "Appearance/behaviour, speech, mood/affect, thought, perception, cognition, insight and risk", ["Only mood", "Only memory", "Only physical examination"], "The MSE is the psychiatric equivalent of the physical examination and should be systematic."),
  Q("y12", "psychiatry", "Psychosis", "differentials", "Before diagnosing a primary psychotic disorder in a newly psychotic patient, you should:", "Exclude substance-induced and medical/neurological causes", ["Assume schizophrenia immediately", "Avoid physical examination", "Ignore medication history"], "First-episode psychosis requires assessment for intoxication/withdrawal, delirium, neurological and metabolic causes."),
  Q("y13", "psychiatry", "Depression", "differentials", "Low mood, loss of interest, poor sleep, low energy, guilt and impaired concentration for several weeks suggest:", "Major depressive episode", ["Mania", "Delirium", "ADHD"], "Depression is a syndrome; always assess function, psychotic features, bipolar history and suicide risk."),
  Q("y14", "psychiatry", "Risk", "management", "A patient says, ‘I have tablets at home and plan to take them tonight.’ The most important next step is:", "Treat this as high suicide risk and ensure immediate safety with urgent psychiatric assessment", ["Promise secrecy and discharge", "Tell them to cheer up", "Avoid asking further questions"], "Specific plan, means and near-term intent substantially increase risk; safety and supervised assessment come first."),
  Q("y15", "psychiatry", "Mood", "differentials", "Why must you ask about previous periods of elevated mood in a patient presenting with depression?", "To identify possible bipolar disorder", ["To diagnose dementia", "To exclude appendicitis", "To measure IQ"], "Missing previous mania/hypomania can lead to an incorrect unipolar-depression formulation and inappropriate treatment."),
  Q("y16", "psychiatry", "Substance", "differentials", "Tremor, sweating, agitation, tachycardia and hallucinations after stopping heavy alcohol use suggest:", "Alcohol withdrawal", ["Opioid intoxication", "Major depression", "Autism"], "Autonomic hyperactivity after cessation is withdrawal; seizures and delirium tremens are dangerous complications."),
  Q("y17", "psychiatry", "Cognition", "differentials", "Which feature favours delirium over dementia?", "Acute onset with fluctuating attention and consciousness", ["Slow progressive memory decline", "Stable alertness", "Years of gradual decline"], "Attention and arousal fluctuate in delirium; identify and treat the underlying medical cause."),
  Q("y18", "psychiatry", "Pharmacology", "management", "Fever, severe rigidity, autonomic instability and altered consciousness after an antipsychotic suggest:", "Neuroleptic malignant syndrome", ["Simple anxiety", "Tardive dyskinesia", "Panic attack"], "NMS is a medical emergency: stop the causative drug and provide urgent supportive/specialist management."),
  Q("y19", "psychiatry", "Pharmacology", "management", "A patient taking an antipsychotic develops painful neck spasm and upward eye deviation. This is:", "Acute dystonia", ["Akathisia", "Tardive dyskinesia", "Mania"], "Acute dystonia can occur early after dopamine blockade and needs prompt anticholinergic treatment."),
  Q("y20", "psychiatry", "Interview", "management", "When interviewing an agitated psychiatric patient, the safest initial style is:", "Calm, non-confrontational de-escalation while assessing immediate risk and maintaining an exit/safe environment", ["Argue with delusions", "Crowd the patient", "Turn your back and block the exit"], "Safety and verbal de-escalation come before coercive measures whenever feasible; assess risk to self and others continuously."),
];
