import { useEffect, useState } from "react";
import { Link, Navigate, useParams } from "react-router-dom";
import { ArrowLeft, Loader2, Route } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { getContestBySlug, getMyContestRegistration, loadMyContestAdvancements, loadMyContestAppeals, loadMyContestAttempts, submitContestAppeal, type ContestAdvancement, type ContestAppeal, type ContestAttempt, type ContestRegistration } from "@/lib/contest-store";

export default function ContestProgress() {
  const { slug = "" } = useParams(), { user, loading: authLoading } = useAuth();
  const [items, setItems] = useState<ContestAdvancement[]>([]), [loading, setLoading] = useState(true), [missing, setMissing] = useState(false);
  const [registration, setRegistration] = useState<ContestRegistration | null>(null), [contestId, setContestId] = useState(""), [attempts, setAttempts] = useState<ContestAttempt[]>([]), [appeals, setAppeals] = useState<ContestAppeal[]>([]);
  const [target, setTarget] = useState(""), [category, setCategory] = useState<ContestAppeal["category"]>("integrity"), [statement, setStatement] = useState(""), [message, setMessage] = useState("");
  useEffect(() => { if (!user || authLoading) return; getContestBySlug(slug).then(async (contest) => { if (!contest) return setMissing(true); setContestId(contest.id); const entry = await getMyContestRegistration(contest.id, user.id); if (!entry) return setMissing(true); setRegistration(entry); const [decisions, attemptRows, appealRows] = await Promise.all([loadMyContestAdvancements(contest.id, entry.id), loadMyContestAttempts(entry.id), loadMyContestAppeals(contest.id)]); setItems(decisions); setAttempts(attemptRows); setAppeals(appealRows); const first = decisions[0] ? `advancement:${decisions[0].id}` : attemptRows[0] ? `attempt:${attemptRows[0].id}` : ""; setTarget(first); }).finally(() => setLoading(false)); }, [authLoading, slug, user]);
  if (!authLoading && !user) return <Navigate to="/login" replace />;
  if (authLoading || loading) return <div className="flex min-h-[70vh] items-center justify-center bg-[#071315]"><Loader2 className="h-6 w-6 animate-spin text-teal-300" /></div>;
  if (missing) return <Navigate to={`/contests/${slug}/lobby`} replace />;
  async function submit() { if (!registration || !target) return; setMessage(""); const [kind, id] = target.split(":"); try { await submitContestAppeal({ contestId, registrationId: registration.id, attemptId: kind === "attempt" ? id : null, advancementId: kind === "advancement" ? id : null, category, statement }); setAppeals(await loadMyContestAppeals(contestId)); setStatement(""); setMessage("Your appeal was submitted for moderator review."); } catch (cause: any) { setMessage(cause?.message || "Appeal could not be submitted."); } }
  return <div className="min-h-dvh bg-[#071315] px-5 py-10 text-white"><div className="mx-auto max-w-3xl"><Link to={`/contests/${slug}/lobby`} className="inline-flex items-center gap-2 text-sm text-white/50"><ArrowLeft className="h-4 w-4" /> Contest lobby</Link><header className="mt-7 rounded-2xl border border-white/10 bg-white/[0.035] p-6"><Route className="h-7 w-7 text-teal-300" /><h1 className="mt-3 font-serif text-3xl font-bold">My contest progression</h1><p className="mt-2 text-sm text-white/50">Only you and authorised contest administrators can see these decisions.</p></header><div className="mt-6 space-y-3">{items.length ? items.map((item) => <article key={item.id} className="rounded-xl border border-white/10 bg-white/[0.035] p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">{item.contest_rounds?.title || "Contest round"}</h2><span className="rounded-full border border-teal-300/20 px-3 py-1 text-xs font-bold capitalize text-teal-200">{item.decision}</span></div><p className="mt-3 text-sm text-white/60">{item.reason}</p></article>) : <p className="rounded-xl border border-dashed border-white/15 p-8 text-center text-sm text-white/45">No progression decision has been published for you yet.</p>}</div>
    {(items.length > 0 || attempts.length > 0) && <section className="mt-7 rounded-2xl border border-white/10 bg-white/[0.035] p-6"><h2 className="font-bold">Submit an appeal</h2><p className="mt-2 text-xs text-white/45">One open appeal is allowed per attempt or decision. Explain the specific factual or technical concern.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><select value={target} onChange={(e) => setTarget(e.target.value)} className="rounded-md border border-white/15 bg-[#0b1b1d] px-3 py-2 text-sm">{items.map((item) => <option key={item.id} value={`advancement:${item.id}`}>{item.contest_rounds?.title || "Round"} decision</option>)}{attempts.map((attempt) => <option key={attempt.id} value={`attempt:${attempt.id}`}>Attempt · {attempt.status}</option>)}</select><select value={category} onChange={(e) => setCategory(e.target.value as ContestAppeal["category"])} className="rounded-md border border-white/15 bg-[#0b1b1d] px-3 py-2 text-sm"><option value="integrity">Integrity</option><option value="score">Score</option><option value="advancement">Advancement</option><option value="technical">Technical</option></select></div><textarea value={statement} onChange={(e) => setStatement(e.target.value)} maxLength={2000} rows={5} placeholder="Describe what happened and why the decision should be reviewed…" className="mt-3 w-full rounded-md border border-white/15 bg-[#0b1b1d] p-3 text-sm" /><button disabled={statement.trim().length < 20} onClick={() => void submit()} className="mt-3 rounded-lg bg-teal-300 px-4 py-2.5 text-sm font-bold text-[#071315] disabled:opacity-40">Submit appeal</button>{message && <p className="mt-3 text-sm text-teal-200">{message}</p>}</section>}
    <section className="mt-7"><h2 className="font-bold">Appeal history</h2><div className="mt-3 space-y-3">{appeals.length ? appeals.map((appeal) => <article key={appeal.id} className="rounded-xl border border-white/10 p-4"><div className="flex justify-between gap-3"><span className="text-xs font-bold uppercase text-teal-200">{appeal.category}</span><span className="text-xs capitalize text-white/50">{appeal.status}</span></div><p className="mt-2 text-sm text-white/60">{appeal.statement}</p>{appeal.resolution && <p className="mt-3 rounded-lg bg-white/5 p-3 text-sm"><strong>Resolution:</strong> {appeal.resolution}</p>}</article>) : <p className="mt-3 text-sm text-white/45">No appeals submitted.</p>}</div></section></div></div>;
}
