// More drugs, added so the study notes link to a real drug card: respiratory, antibacterials, anticoagulation,
// bipolar disorder and lung cancer. Teaching doses only: always follow the national guideline and the hospital formulary.
import type { PDrug } from "./types";
import { BLOOD, CNS, INF, RESP } from "./drugsCommon";
import { TARGET } from "./drugsOnc";

const p = (group: string, id: string, name: string, cls: string, why: string, mech: string, ae: string[], caution: string, dose: string, special: string): PDrug => ({ group, id, name, cls, why, mech, ae, caution, dose, special });

export const MORE_DRUGS: PDrug[] = [
  // ---- lungs
  p(RESP, "tiotropium", "Tiotropium", "Long-acting antimuscarinic (LAMA)", "Maintenance bronchodilator in COPD; add-on in severe asthma.", "Blocks M3 muscarinic receptors in airway smooth muscle for about 24 hours, preventing vagal bronchoconstriction.", ["Dry mouth", "Urinary retention in older men with an enlarged prostate", "Constipation", "Raised eye pressure if the mist reaches the eyes"], "Narrow-angle glaucoma and bladder outflow obstruction.", "18 µg once daily by HandiHaler, or 2 puffs of 2.5 µg once daily by Respimat.", "Not for rescue use. Combine with a LABA in more symptomatic COPD."),
  p(RESP, "budesonide-formoterol", "Budesonide–formoterol", "Inhaled corticosteroid plus long-acting β₂-agonist (ICS-LABA)", "Asthma preventer and, in MART, the reliever as well; COPD with frequent exacerbations and high eosinophils.", "Budesonide reduces airway inflammation; formoterol relaxes smooth muscle within minutes and for about 12 hours.", ["Tremor, palpitations and low potassium", "Oral thrush and hoarse voice", "Headache"], "Never use a LABA alone in asthma; care in tachyarrhythmia and thyrotoxicosis.", "Asthma: 1–2 inhalations twice daily; as reliever 1 inhalation when needed, up to the daily maximum in the product guideline.", "Rinse the mouth after use. Check inhaler technique and use a spacer if needed."),
  p(RESP, "montelukast", "Montelukast", "Leukotriene receptor antagonist", "Add-on in asthma, especially with allergic rhinitis or exercise-induced symptoms, when an inhaled steroid alone is not enough.", "Blocks the cysteinyl leukotriene (CysLT1) receptor, reducing bronchoconstriction, mucus and airway oedema.", ["Headache and abdominal pain", "Sleep disturbance and vivid dreams", "Mood change, anxiety, depression and rarely suicidal thoughts"], "Psychiatric history: counsel the patient to report mood or behaviour change.", "10 mg once daily at night (adults); 5 mg chewable at 6–14 years.", "Not a rescue drug."),
  p(RESP, "aminophylline", "Aminophylline / theophylline", "Methylxanthine bronchodilator", "Severe asthma or COPD exacerbation that has not responded to nebulised bronchodilators (IV, senior or ICU decision).", "Inhibits phosphodiesterase and blocks adenosine receptors, relaxing airway smooth muscle.", ["Palpitations and arrhythmia", "Nausea and vomiting", "Tremor, anxiety and insomnia", "Seizures in overdose", "Low potassium"], "Narrow therapeutic index (level 10–20 mg/L). Clarithromycin, ciprofloxacin and oral contraceptives raise levels; smoking lowers them. Heart failure and liver disease.", "IV loading 5 mg/kg over 20 minutes (omit if already taking theophylline), then 0.5 mg/kg/hour, adjusted to the level.", "Rarely used now because magnesium and other options are safer. Always check the level."),
  p(RESP, "roflumilast", "Roflumilast", "Phosphodiesterase-4 inhibitor", "Severe COPD with chronic bronchitis and frequent exacerbations despite inhaled treatment.", "Inhibits PDE-4, raising cAMP in inflammatory cells and reducing airway inflammation.", ["Diarrhoea, nausea and weight loss", "Headache, insomnia, anxiety and depression", "Back pain"], "Psychiatric history or suicidal thoughts, moderate to severe liver disease, underweight.", "500 µg once daily (250 µg for the first 4 weeks).", "Not a bronchodilator: add it to inhalers, not instead of them."),
  p(RESP, "nintedanib", "Nintedanib", "Tyrosine kinase inhibitor (antifibrotic)", "Idiopathic pulmonary fibrosis and other progressive fibrosing lung diseases; slows the fall in lung function.", "Blocks VEGF, FGF and PDGF receptor kinases that drive fibroblast growth and collagen deposition.", ["Diarrhoea (very common)", "Nausea and vomiting", "Raised liver enzymes", "Bleeding", "Rare gut perforation"], "Liver impairment, anticoagulants, recent abdominal surgery, pregnancy (teratogenic).", "150 mg twice daily with food; 100 mg twice daily if not tolerated.", "Slows but does not reverse fibrosis. Liver tests monthly for 3 months, then every 3 months."),
  p(RESP, "pirfenidone", "Pirfenidone", "Antifibrotic (pyridone)", "Idiopathic pulmonary fibrosis: slows the decline in forced vital capacity.", "Reduces fibroblast proliferation and collagen synthesis (exact mechanism uncertain).", ["Nausea and dyspepsia", "Photosensitivity rash", "Fatigue, anorexia and weight loss", "Raised liver enzymes"], "Severe liver or kidney impairment; CYP1A2 interactions (fluvoxamine, ciprofloxacin).", "Titrate over 2 weeks to 801 mg three times daily with food.", "Sunscreen and covering the skin are essential."),
  // ---- antibacterials
  p(INF, "amoxicillin", "Amoxicillin", "Aminopenicillin (β-lactam)", "First-line for community-acquired pneumonia, otitis media, sinusitis, tonsillitis and many urinary infections; also in H. pylori regimens.", "Binds penicillin-binding proteins and blocks bacterial cell-wall synthesis.", ["Diarrhoea and nausea", "Rash (a non-allergic rash is common in glandular fever)", "Anaphylaxis in penicillin allergy", "C. difficile colitis"], "Penicillin allergy; reduce the dose in renal impairment.", "500 mg–1 g three times daily orally; for pneumonia usually 5 days.", "Safe in pregnancy and breast-feeding. Use co-amoxiclav where β-lactamase producers are likely."),
  p(INF, "clarithromycin", "Clarithromycin", "Macrolide", "Atypical cover in community-acquired pneumonia (with a β-lactam), H. pylori regimens, and an alternative in penicillin allergy.", "Binds the 50S ribosome and blocks protein synthesis.", ["Nausea, diarrhoea and a metallic taste", "QT prolongation", "Raised liver enzymes", "Many interactions (strong CYP3A4 inhibitor)"], "Raises levels of statins, warfarin, theophylline, carbamazepine and digoxin; long QT.", "500 mg twice daily orally or IV.", "Avoid with simvastatin."),
  p(INF, "clindamycin", "Clindamycin", "Lincosamide", "Lung abscess, aspiration pneumonia, bone and soft-tissue infection, toxic shock (reduces toxin production) and penicillin allergy.", "Binds the 50S ribosome and blocks protein synthesis.", ["Diarrhoea and C. difficile colitis (the highest risk of any antibiotic)", "Rash", "Metallic taste"], "Previous C. difficile; stop and test if severe diarrhoea develops.", "300–450 mg four times daily orally; 600–900 mg IV every 8 hours.", "Penetrates bone and abscesses well."),
  p(INF, "flucloxacillin", "Flucloxacillin", "Anti-staphylococcal penicillin", "Skin and soft-tissue infection, bone and joint infection, staphylococcal pneumonia and endocarditis caused by MSSA.", "A β-lactamase-stable penicillin that blocks cell-wall synthesis.", ["Cholestatic jaundice (can appear weeks after stopping)", "Diarrhoea", "Rash and allergy"], "Penicillin allergy, previous flucloxacillin liver injury; MRSA is resistant.", "500 mg–1 g four times daily orally; 1–2 g IV every 6 hours.", "Take on an empty stomach."),
  // ---- clotting
  p(BLOOD, "apixaban", "Apixaban", "Direct oral anticoagulant (factor Xa inhibitor)", "Treatment and prevention of DVT and pulmonary embolism, and stroke prevention in non-valvular atrial fibrillation.", "Directly and reversibly inhibits factor Xa, reducing thrombin generation.", ["Bleeding (gut, urinary tract, nose)", "Anaemia", "Nausea"], "Severe kidney or liver disease; mechanical valves and antiphospholipid syndrome (use warfarin); rifampicin, carbamazepine and strong CYP3A4 inhibitors; pregnancy.", "VTE: 10 mg twice daily for 7 days, then 5 mg twice daily. AF: 5 mg twice daily (2.5 mg if two of age 80 or over, weight 60 kg or less, creatinine 133 µmol/L or more).", "Andexanet alfa reverses it. No routine monitoring."),
  // ---- brain and mood
  p(CNS, "quetiapine", "Quetiapine", "Atypical (second-generation) antipsychotic", "Mania, bipolar depression, schizophrenia and as an add-on in depression.", "Blocks dopamine D2 and serotonin 5-HT2A receptors, with strong H1 and α1 blockade; its active metabolite also inhibits noradrenaline reuptake.", ["Sedation and dizziness", "Weight gain, high glucose and lipids", "Postural hypotension", "Dry mouth and constipation", "QT prolongation"], "Metabolic syndrome, heart disease, older people with dementia (higher mortality). Monitor weight, glucose and lipids.", "Bipolar depression 300 mg at night; mania 400–800 mg daily in divided doses, titrated over days; schizophrenia 300–450 mg daily.", "Very sedating at low doses: give at night."),
  p(CNS, "lamotrigine", "Lamotrigine", "Anticonvulsant and mood stabiliser", "Maintenance treatment in bipolar disorder (prevents depressive relapse), and focal and generalised epilepsy.", "Blocks voltage-gated sodium channels and reduces glutamate release.", ["Rash, including Stevens–Johnson syndrome and toxic epidermal necrolysis", "Headache, dizziness and double vision", "Insomnia"], "Titrate slowly. Valproate doubles its level (halve the dose); the combined pill lowers it. Stop at any rash.", "Bipolar: 25 mg daily for 2 weeks, 50 mg for 2 weeks, then increase to a target of 200 mg (100 mg with valproate).", "If it is missed for more than 5 half-lives, restart the titration from the beginning."),
  // ---- cancer
  p(TARGET, "osimertinib", "Osimertinib", "EGFR tyrosine kinase inhibitor (third generation)", "EGFR-mutant non-small cell lung cancer, including T790M resistance; first-line and adjuvant use.", "Irreversibly blocks mutant EGFR (exon 19 deletion, L858R and T790M) while sparing wild-type EGFR.", ["Rash and dry skin", "Diarrhoea", "Paronychia (inflamed nail folds)", "Interstitial lung disease (stop if it develops)", "QT prolongation and cardiomyopathy"], "Confirm the EGFR mutation first; report new cough or breathlessness; pregnancy.", "80 mg once daily orally.", "Tablets can be dispersed in water for patients who cannot swallow."),
  p(TARGET, "pembrolizumab", "Pembrolizumab", "PD-1 checkpoint inhibitor (monoclonal antibody)", "Non-small cell lung cancer with high PD-L1, melanoma and many other cancers, alone or with chemotherapy.", "Blocks the PD-1 receptor on T cells, so tumour cells can no longer switch off the immune response.", ["Fatigue, rash and itching", "Immune-related colitis, pneumonitis, hepatitis, thyroid and adrenal disease, type 1 diabetes", "Infusion reactions"], "Active autoimmune disease, organ transplant, pregnancy. Treat immune toxicity early with steroids.", "200 mg every 3 weeks or 400 mg every 6 weeks by IV infusion.", "Check thyroid, liver, cortisol and glucose before each cycle."),
];
